/**
 * Interactive setup wizard (pure helpers + runner).
 *
 * The wizard (`piren setup` with no flags) guides an operator through:
 *   1. Vault: existing (detect agents, enable/disable) or new (init + first agent).
 *   2. LLM: pick a Pi provider, enter the key, write ~/.pi/agent/auth.json at 0600.
 *   3. (Optional) gateways + service install.
 *
 * The pure helpers here are unit-tested directly (tests/wizard.test.ts). The
 * impure runner `runWizard(prompt, deps)` takes an injected WizardPrompt and fs
 * deps, so tests drive it with a fake prompter and a tmpdir. The real readline
 * implementation lives in src/prompt.ts.
 */

import { mkdir, readFile, writeFile, chmod, access, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { homedir } from "node:os";
import type { WizardPrompt } from "./prompt.js";
import { initVault } from "./init.js";

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/**
 * Known Pi providers with their api-key env var, reverse-engineered from the
 * pinned Pi source (packages/ai/src/providers/*.ts). The wizard uses this to
 * offer accurate env-var guidance and to write the auth.json entry keyed by the
 * Pi provider id.
 */
export interface PiProviderInfo {
  id: string;
  name: string;
  envVar: string;
  /** A default model id hint for the agent-local config.yml, Pi's `<provider>/<model>:<thinking>` form. */
  defaultModel?: string;
}

export const PI_PROVIDERS: readonly PiProviderInfo[] = [
  { id: "anthropic", name: "Anthropic (Claude)", envVar: "ANTHROPIC_API_KEY", defaultModel: "anthropic/claude-sonnet-4-20250514:medium" },
  { id: "openai", name: "OpenAI", envVar: "OPENAI_API_KEY" },
  { id: "google", name: "Google (Gemini)", envVar: "GEMINI_API_KEY" },
  { id: "deepseek", name: "DeepSeek", envVar: "DEEPSEEK_API_KEY" },
  { id: "groq", name: "Groq", envVar: "GROQ_API_KEY" },
  { id: "mistral", name: "Mistral", envVar: "MISTRAL_API_KEY" },
  { id: "xai", name: "xAI (Grok)", envVar: "XAI_API_KEY" },
  { id: "openrouter", name: "OpenRouter", envVar: "OPENROUTER_API_KEY" },
];

export function formatProviderMenu(): string {
  const lines: string[] = ["Choose a Pi provider:"];
  PI_PROVIDERS.forEach((provider, index) => {
    lines.push(`${index + 1}. ${provider.name} (${provider.id}) — key via ${provider.envVar}`);
  });
  return lines.join("\n");
}

/**
 * Detect whether a path is an existing Piren vault. Mirrors the bootstrap
 * detection heuristic: the `.piren-vault` marker, or `steward-directives.md`
 * alongside a `team/` directory.
 */
export async function isExistingVault(path: string): Promise<boolean> {
  try {
    await access(join(path, ".piren-vault"));
    return true;
  } catch {
    // fall through
  }
  try {
    await access(join(path, "steward-directives.md"));
    await access(join(path, "team"));
    return true;
  } catch {
    return false;
  }
}

export type AuthJsonCredential = { type: "api_key"; key: string };

/**
 * Build a single-provider auth.json fragment keyed by provider id. This matches
 * Pi's on-disk shape: Record<providerId, {type, key}>.
 */
export function buildAuthJsonEntry(providerId: string, apiKey: string): Record<string, AuthJsonCredential> {
  return { [providerId]: { type: "api_key", key: apiKey } };
}

/**
 * Merge a new auth entry into an existing auth.json object and serialize to the
 * 2-space-indented JSON Pi expects. Existing providers are preserved.
 */
export function serializeAuthJson(existing: Record<string, AuthJsonCredential>, entry: Record<string, AuthJsonCredential>): string {
  const merged: Record<string, AuthJsonCredential> = { ...existing };
  for (const [key, value] of Object.entries(entry)) {
    merged[key] = value;
  }
  return JSON.stringify(merged, null, 2) + "\n";
}

export interface LocalConfigInput {
  vaultRoot: string;
  allowedAgents: string[];
  excludedAgents: string[];
}

/**
 * Build the ~/.config/piren/config.yml content from wizard input. This is the
 * same shape `piren setup --apply` writes, extended to support multiple allowed
 * agents and an excluded list (useful when adopting an existing vault).
 */
export function buildLocalConfigPatch(input: LocalConfigInput): string {
  const lines: string[] = [
    "# Piren installation config — generated by piren setup wizard",
    `vault_root: ${input.vaultRoot}`,
    "",
    "allowed_agents:",
  ];
  for (const agent of input.allowedAgents) {
    lines.push(`  - ${agent}`);
  }
  if (input.excludedAgents.length > 0) {
    lines.push("");
    lines.push("excluded_agents:");
    for (const agent of input.excludedAgents) {
      lines.push(`  - ${agent}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * Parse a comma-separated string into a trimmed, de-blanked array. Used by the
 * wizard when the operator enters multiple agents in one line.
 */
export function parseCommaList(input: string): string[] {
  return input
    .split(",")
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
}

// ---------------------------------------------------------------------------
// Runner (impure; deps injected)
// ---------------------------------------------------------------------------

const AGENT_NAME_PATTERN = /^[a-z][a-z0-9-]*$/;

export interface WizardDeps {
  configPath?: string;
  piHome?: string;
  log?: (message: string) => void;
}

export interface WizardResult {
  vaultRoot: string;
  allowedAgents: string[];
  excludedAgents: string[];
  newVault: boolean;
  providerId?: string;
  wroteAuthJson: boolean;
  wroteConfig: boolean;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function readAuthJson(piHome: string): Promise<Record<string, AuthJsonCredential>> {
  const authPath = join(piHome, "auth.json");
  if (!(await pathExists(authPath))) return {};
  try {
    const content = await readFile(authPath, "utf8");
    const parsed = JSON.parse(content) as unknown;
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, AuthJsonCredential>;
    }
    return {};
  } catch {
    return {};
  }
}

export async function runWizard(prompt: WizardPrompt, deps: WizardDeps = {}): Promise<WizardResult> {
  const log = deps.log ?? ((message: string) => console.log(message));
  const configPath = deps.configPath ?? join(homedir(), ".config", "piren", "config.yml");
  const piHome = deps.piHome ?? join(homedir(), ".pi", "agent");

  log("Welcome to Piren setup. This wizard configures your vault, LLM provider, and local config.");
  log("");

  // --- Step 1: Vault ---
  const vaultAnswer = await prompt.text("Path to your Piren vault", process.cwd());
  const vaultRoot = resolve(vaultAnswer);

  let allowedAgents: string[] = [];
  let excludedAgents: string[] = [];
  let newVault = false;

  if (await isExistingVault(vaultRoot)) {
    newVault = false;
    log(`Found an existing vault at ${vaultRoot}.`);
    // Detect agents under team/.
    const teamDir = join(vaultRoot, "team");
    let vaultAgents: string[] = [];
    if (await pathExists(teamDir)) {
      const entries = await readdir(teamDir, { withFileTypes: true });
      vaultAgents = entries
        .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
        .map((entry) => entry.name)
        .sort((a, b) => a.localeCompare(b));
    }
    if (vaultAgents.length === 0) {
      log("No agents found under team/. You can still proceed; configure allowed_agents manually.");
      const first = await prompt.text("Name the first agent for this vault", "piren");
      if (!AGENT_NAME_PATTERN.test(first)) {
        throw new Error("Invalid agent name. Use lowercase kebab-case, for example 'piren'.");
      }
      await initVault({ vaultRoot, agentName: first });
      allowedAgents = [first];
      excludedAgents = [];
    } else {
      log("Existing agents: " + vaultAgents.join(", "));
      const selected = await prompt.list("Which agents should this installation be allowed to run? (comma-separated)", vaultAgents.length === 1 ? vaultAgents : undefined);
      allowedAgents = selected.length > 0 ? selected : vaultAgents;
      const excluded = await prompt.list("Any agents to exclude on this installation? (comma-separated, or leave blank)", []);
      excludedAgents = excluded;
    }
  } else {
    newVault = true;
    log(`${vaultRoot} is not an existing vault. A new vault will be initialized there.`);
    const firstAgent = await prompt.text("Name the first agent", "piren");
    if (!AGENT_NAME_PATTERN.test(firstAgent)) {
      throw new Error("Invalid agent name. Use lowercase kebab-case, for example 'piren'.");
    }
    await initVault({ vaultRoot, agentName: firstAgent });
    log(`Initialized vault at ${vaultRoot} with agent '${firstAgent}'.`);
    allowedAgents = [firstAgent];
    excludedAgents = [];
  }

  log("");

  // --- Step 2: LLM provider + key ---
  let providerId: string | undefined;
  let wroteAuthJson = false;
  const setupLlm = await prompt.confirm("Configure a Pi LLM provider and API key now?", true);
  if (setupLlm) {
    log(formatProviderMenu());
    const idx = await prompt.select("Provider", PI_PROVIDERS.map((p) => `${p.name} (${p.id})`), 0);
    const provider = PI_PROVIDERS[idx] ?? PI_PROVIDERS[0]!;
    providerId = provider.id;
    const key = await prompt.secret(`Enter your ${provider.name} API key (${provider.envVar})`);
    if (key.trim() === "") {
      log("No key entered. Skipping auth.json write; you can set it later with Pi's login or an env var.");
    } else {
      const existing = await readAuthJson(piHome);
      const entry = buildAuthJsonEntry(provider.id, key.trim());
      const serialized = serializeAuthJson(existing, entry);
      await mkdir(piHome, { recursive: true });
      const authPath = join(piHome, "auth.json");
      await writeFile(authPath, serialized, "utf8");
      await chmod(authPath, 0o600);
      wroteAuthJson = true;
      log(`Wrote ${provider.name} key to ${authPath} (mode 0600).`);
    }
  }

  log("");

  // --- Step 3: write local config ---
  const configContent = buildLocalConfigPatch({ vaultRoot, allowedAgents, excludedAgents });
  log("The following will be written to " + configPath + ":");
  log(configContent
    .split("\n")
    .map((line) => "  " + line)
    .join("\n"));
  const confirmWrite = await prompt.confirm("Write this configuration?", true);
  let wroteConfig = false;
  if (confirmWrite) {
    await mkdir(dirname(configPath), { recursive: true });
    await writeFile(configPath, configContent, "utf8");
    wroteConfig = true;
    log(`Wrote ${configPath}.`);
  } else {
    log("Skipped writing local config. Re-run piren setup when ready.");
  }

  log("");
  log("Setup complete. Next steps:");
  log(`  piren doctor`);
  if (allowedAgents.length === 1) {
    log(`  piren --vault-root ${vaultRoot} --agent ${allowedAgents[0]!} run`);
  } else {
    log(`  piren --vault-root ${vaultRoot} --agent ${allowedAgents[0]!} run  (or pick from: ${allowedAgents.join(", ")})`);
  }

  const result: WizardResult = {
    vaultRoot,
    allowedAgents,
    excludedAgents,
    newVault,
    wroteAuthJson,
    wroteConfig,
  };
  if (providerId !== undefined) result.providerId = providerId;
  return result;
}
